version: '3.8'

services:
  backend:
    image: ashyrmalik/taskmgr-backend:latest
    container_name: taskmanager-backend
    ports:
      - "3000:3000"  # Host port:Container port (adjust based on your backend)
    environment:
      - MONGO_URI=mongodb+srv://ashar:wwe@cluster0.3xere.mongodb.net/taskmanager?retryWrites=true&w=majority
    restart: always

  frontend:
    image: ashyrmalik/taskmgr-frontend:latest
    container_name: taskmanager-frontend
    ports:
      - "3001:80"  # Frontend on port 3000
    restart: always

# Removed the "mongo" service since you're using Atlas
