version: '3.8'

services:
  backend:
    image: ashyrmalik/taskmgr-backend:latest
    container_name: taskmanager-backend
    ports:
      - '3000:3000'
    environment:
      - MONGO_URI="mongodb+srv://ashar:wwe@cluster0.3xere.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0"
    depends_on:
      - mongo
    restart: always

  frontend:
    image: ashyrmalik/taskmgr-frontend:latest
    container_name: taskmanager-frontend
    ports:
      - '3001:80'
    depends_on:
      - backend
    restart: always

  mongo:
    image: mongo:6
    container_name: taskmanager-mongo
    ports:
      - '27017:27017'
    volumes:
      - mongo-data:/data/db
    restart: always

volumes:
  mongo-data: 
